modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="sky_ages"
version="0.0.0.2"
displayName="Sky ages"
displayURL="https://mcreator.net"
credits="I use Mcreator to speed up the dev time since I'm alone."
authors="Switchot"
description="Pre-Alpha of a mods very big"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sky_ages]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sky_ages]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration